// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL")?.includes("localhost")
      ? env("DATABASE_URL")?.replace("localhost", "127.0.0.1").replace(":5432", ":5433")
      : env("DATABASE_URL"),
    directUrl: process.env.DIRECT_URL
      ? (process.env.DIRECT_URL.includes("localhost")
        ? process.env.DIRECT_URL.replace("localhost", "127.0.0.1").replace(":5432", ":5433")
        : process.env.DIRECT_URL)
      : undefined,
  },
});
